### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by jevi061** [Fagrell/qml-editor#1]
Hi Mr.Fagrell,I cant find a entry to leave a comment in your blog,so here I have a question about Mvc pattern you use in your last blog.

https://stackoverflow.com/questions/36433149/mvc-and-subject-observer-pattern-in-c-qt/36611504#36611504
here you suggestion  a variations of ios's mvc,and I also prefer it,but you post a picture of new style of mvc in ur crash qt course which I think is confusing,cause in many other place ,I got the  idea that the view shoud know nothing about the controller,and both view and model are independent and communicate through controller each other.

the book you mentioned use the same pattern with you have posted.

so can you tell me why you choose new style mvc pattern now?

what is advatage?

thx for post qt blog and share with us.

**Comment by Fagrell** [comment]
Hey Jevi,

Thanks for a great question! 

In general, I believe both are great structures as long as you are consistently using one through out the code.
The reason I now prefer the style presented in the last blog post, is because it makes it easier to have a really thin front-end consisting of the view alone. 
The controller doesn't need to know about the view. In addition, it's easy to keep the view updated with the model without having a middle layer (the controller). This is similar to how the  Model-View operates in Qt. If further decoupling is needed you can always add interfaces for the controller and model (to inverse the dependency).

Also note that there is a "thin" traditional controller baked into the view. This controller only forwards user actions down to the back-end controller which then direct the flow.

I'll make sure I update med stackoverflow answer.

Cheers, Alex
